### ISSUE TITLE
3D object export

### ISSUE THREAD

**Issue by AndrewLyon** [SynapseWeb/PyReconstruct#18]
**Is your feature request related to a problem? Please describe.**
Problem related. PyReconstruct is missing export options that the non-python version does not have. With the previous version, my lab would render the object we need, then export that directly from the scene into a vrml 2.0 file directly for use with Amira.

**Describe the solution you'd like**
The option to export 3D objects in file types such as .vrml (which is supported with the legacy version) and/or other supported 3D file options. Maybe also allow an object in the object list to be exported into a vrml file without having to render it first?

**Describe alternatives you've considered**
Have considered file converters, and importing through object lists as csv files. The current solution is to convert the pyreconstruct object into a legacy object, and then export it (as stated above). 

**Additional context**

**Comment by quasiTriestino** [comment]
Thank you for your feature request. We've been meaning to do this for a while and you've provided some outside impetus that put us over the threshold to get it done.

You can now (as of commit `ec7560b`) export 3D objects by selecting one or several objects in the object list, right-clicking, and selecting 3D > Export. You will be prompted to select a folder where you would like to save the exported object(s). Each exported file is named according to the object name. I tested the exported files by importing into Blender 4.0, and they seem to work great.

You can export objects as .obj, .off, .ply, .stl natively. From what I can tell online, it looks like Amira imports ply format. We can add vrml and x3d formats to the export options, but this would necessitate us moving to pymeshlab, a pretty hefty package compared to trimesh, which PyReconstruct currently uses to generate the triangle mesh.

Let us know how it goes and if ply is sufficient for your needs and thanks!

**Comment by AndrewLyon** [comment]
Thank you for the quick response!

I was able to successfully convert the objects into  the ply format and successfully import that into Amira. I have tested the export process on arm64 macos and both windows 11 and 10 with success. Thanks again!

________________________________
