### ISSUE TITLE
Closed Trace Type Selection

### ISSUE THREAD

**Issue by AndrewLyon** [SynapseWeb/PyReconstruct#20]
**Is your feature request related to a problem? Please describe.**
Feature request -- quality of life issue. When using a mouse or pen to trace a section, double clicking or double pressing will change the closed tracing tool from freehand to a line based tracing selection. When tracing with a pen and that pen registers a double press, it will mess with the flow of the work. Additionally, if the user attempts to swap out of the tool (i.e. to reset the closed trace tool back to freehand) it will create an unclosed trace that cannot be merged with the rest of the object. This becomes painful when the user attempts to merge all parts of a trace as it creates an 'unclosed trace' error.

**Describe the solution you'd like**
A way to allow the user to select which tracing style explicitly - either through a setting option or to split the two asa tool.

**Describe alternatives you've considered**
Tracing with a wacom tablet, iPad Pro, mouse only.

**Comment by julian-falco** [comment]
@AndrewLyon As of commit bd44658 on the main branch, I have implemented a feature where you can right-click the closed trace tool button and explicitly set the trace mode you prefer. The method before was "combo," where a click would result in a polygon-style trace, and a click-and-drag would result in a scribble-style trace. Now, you can set your tracing mode to one or the other (or keep it as both). This option is also modifiable through the general series options. Let me know if this helps!

**Comment by AndrewLyon** [comment]
Just tested it out, it works beautifully. Thank you!
