### ISSUE TITLE
3D Object Export Issue

### ISSUE THREAD

**Issue by AndrewLyon** [SynapseWeb/PyReconstruct#21]
**Describe the bug**
When attempting to export a 3D object, errors occur.

**To Reproduce**
1. Trace object to make 3D
2. right click object in object list and export (doesn't matter which file type, issue persists)
3. 'Surface' Object is not subscriptable

**Expected behavior**
Object exports as requested

**Screenshots**
See attached.
[pyrecon_error.txt](https://github.com/SynapseWeb/PyReconstruct/files/14594944/pyrecon_error.txt)

**Desktop (please complete the following information):**
 - OS: Issue originally started on Windows 10 pc. The same dataset errors on other pyreconstruct setups (this dataset only).
 - Most recently updated (as of 03/13/24), version has the trace open/close feature as requested by myself.

**Python (please indicate the version of Python you are using):**
- 3.10,3.11,3.12

**Additional context**
Issue only persists with this one dataset, and applies regardless of presence of open traces. Originally thought the error was due to unclosed traces, but error persists when those open traces are deleted. Further, also assumed that the object being started on two separate ends but not completed within the center was also the error - still persists when half of those traces are removed.

**Comment by quasiTriestino** [comment]
Would you be willing to provide a .jser file here with the offending object? And to confirm: This is only a problem with a single dataset?

**Comment by AndrewLyon** [comment]
.jser direct upload isn't available
Try this:

https://sfsu.box.com/s/nd36rqx5lfqmxhu522el64k8xjrflif3

**Comment by quasiTriestino** [comment]
Awesome - thanks. I'm getting the same error on my end. Let me take a crack at it and I will let you know.

**Comment by quasiTriestino** [comment]
Hello again - Over the past several commits, we added some changes into the 3D scene that broke the exporter. We're working on that right now. For the time being, you can checkout commit ec7560b which is the commit when the exporter was introduced. This will at least let you export your objects until we fix things. Once we've got a patch ready to go, I will update you here. Thanks!

**Comment by quasiTriestino** [comment]
@AndrewLyon: Actually, the fix on my end turned out to be pretty simple. I have pushed changes to the main branch as of commit 83f9ef1bbba865dd320da9b874ea148d4528ed8f. Please let us know if this resolves your problem. Thanks!

**Comment by AndrewLyon** [comment]
Fixed, thank you again for all of your help!
