### ISSUE TITLE
error "PySide6.QtCore.QEvent' object has no attribute 'size'"

### ISSUE THREAD

**Issue by AgatheChaigne** [SynapseWeb/PyReconstruct#25]
### Describe the bug

After installing (manually, on mac), error: "PySide6.QtCore.QEvent' object has no attribute 'size'" and program won't open.

### To Reproduce

Installing collected packages: PyReconstruct
Successfully installed PyReconstruct-0.1.0
Launch PyReconstruct

### Expected behavior

PyReconstruct launches

### Desktop environment:

macOS 14.4.1

### Python version

3.11

### Error messages

AttributeError: 'PySide6.QtCore.QEvent' object has no attribute 'size'

### Screenshots

<img width="748" alt="Screenshot 2024-04-26 at 15 23 35" src="https://github.com/SynapseWeb/PyReconstruct/assets/168198012/7192d7eb-c3bd-4b07-aa57-b4a616bf0156">

**Comment by quasiTriestino** [comment]
@AgatheChaigne Thank you so much for bringing this to our attention. The python wrapper for Qt we use, PySide6, introduced a recent change that broke PyReconstruct. I've specified 6.6.1 in our setup file as of commit 3d85c01, which seems to fix the issue. Would you mind deleting your virtual environment and reinstalling PyReconstruct?

**Comment by AgatheChaigne** [comment]
It works now! Thanks!

**Comment by quasiTriestino** [comment]
Thank you and happy tracing :)
