### ISSUE TITLE
Forked .Zarr conversion

### ISSUE THREAD

**Issue by AndrewLyon** [SynapseWeb/PyReconstruct#26]
### Is your feature request related to a problem? Please describe.
When converting a dataset with hundred of images (mine are .tiff for example), the work is being done by one processor core only - and even then the work is being serially (image is loaded into ram, processed and then sent back out). This takes a lot of time to finish, even when the work is being done on an SSD.

### Describe the solution you'd like
Some ideas:
Images preloaded to system memory before being converted.
Multiple cores can work on different images at the same time.
A combination of the two above.

**Comment by quasiTriestino** [comment]
@AndrewLyon Thanks for the nudge. The multiprocessing pool method in the conversion scripts had been called with an optional argument which limited the conversions to being synchronous. I have lifted this restriction as of commit d136510. Please give it a try. It should be a significant bump in speed. Buyer beware: Until we implement some way of giving the user the option to limit the number of cores used, the conversion will likely slow down your computer as different processes compete for resources. Give it a go and let us know!

**Comment by AndrewLyon** [comment]
Insane speed increase, thanks again for the support!

**Comment by quasiTriestino** [comment]
Excellent! 😃
