### ISSUE TITLE
Multi-Cut Knife Tool

### ISSUE THREAD

**Issue by AndrewLyon** [SynapseWeb/PyReconstruct#27]
### Is your feature request related to a problem? Please describe.

In the older version of Reconstruct, you could use the knife tool on multiple parts of the same object without having to select/deselect anything.

### Describe the solution you'd like

Re-enabling this feature, or allow an option to choose between the two

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by quasiTriestino** [comment]
So I understand correctly, you'd like to be able to cut all objects that fall underneath the knife cut? I can see right now how this is a hassle if you want to keep cutting the same object multiple times, you've got to continually de-select / select.

**Comment by AndrewLyon** [comment]
Yes please!

**Comment by quasiTriestino** [comment]
@AndrewLyon We've implemented this as of commit 316d2aa - You now can cut multiple selected traces of the same name. So if you're cutting an object, you can continue cutting without having to deselect. Give it a try and let us know how it goes. Thanks!

**Comment by AndrewLyon** [comment]
Works beautifully. Thanks again!
