### ISSUE TITLE
feret diameter

### ISSUE THREAD

**Issue by jessholz** [SynapseWeb/PyReconstruct#28]
If possible please add a way of measuring feret diameter of traces.   We use max ferets for our measurements of bouton diameter, it would be super helpful!

thanks

**Comment by quasiTriestino** [comment]
@jessholz Thanks for the suggestion - As of commit 23c6cfe, we have implemented min and max Feret diameters as optional columns in the trace list. To view them, open the trace list by going to `Lists` > `Trace list` (or use the shortcut `Ctrl/Cmd + Shift + T`). With the trace list open, select the columns you would like to view by going to `List` >  `Set columns...`. There you can toggle on and off `Feret`. Feret diameters will only be given for closed traces. If this works out for you, let us know and thanks again - happy tracing!
