### ISSUE TITLE
Renaming alignments clears assigned Object alignments

### ISSUE THREAD

**Issue by dustenhubbard** [SynapseWeb/PyReconstruct#32]
### Describe the bug

When viewing the Modify Alignments window, there is an option to rename an alignment in the list.
If you rename an alignment, any object in the Objects List with that alignment already assigned gets cleared and the user has to manually reassign the object alignment.

### Commit or version

bf171e7

### Desktop environment:

macOS 15.0

### Python version

3.11

### Error messages

none

**Comment by quasiTriestino** [comment]
@dustenhubbard Thanks for giving us the heads up about this. I have implemented a fix that will rename alignments appropriately with commit 36045d7. Be aware that renaming alignments in large series will take a second. (You will get a progress bar.) To get around this, in a future fix, we will move alignments into the hidden .ser file, which should make the process snappier. 

Please give the fix a try and let us know how it goes. Thanks again!
